---
- hosts: docker_servers
  gather_facts: no
  become: true
  vars:
    container_name: go_app
    container_image: rai68/skillbox_app
    host_port: 80
    container_port: 8080
  # copy unit-file
  tasks:
  - name: Copy from Local to Remote Target Machine with 'copy'
    template:
      src: app.service.j2
      dest: /etc/systemd/system/app.service
      owner: root
      group: root
  # reload daemon-reload and start service go_app
  - name: Start service with systemd
    systemd:
      daemon_reload: yes
      name: app.service
      state: started
      enabled: yes